Repository ComPWA/tensorwaves, pull requests merged in 2020-06, with the labels that each got.

#71 feat: add Blatt-Weisskopf barrier factor option
  doc/contribute.rst
  examples/intensity-recipe.yaml
  requirements.txt
  tensorwaves/physics/helicityformalism/amplitude.py
  tensorwaves/physics/helicityformalism/kinematics.py
Labels: Priority: High, Type: Enhancement

#75 ci: fix Sphinx linkcheck issues
  doc/conf.py
  doc/requirements.txt
  examples/jupyter/generate.ipynb
Labels: Type: Bug, documentation

#76 refactor: switch to typing.NamedTuple
  tensorwaves/physics/helicityformalism/amplitude.py
Labels: Priority: Low, Type: Maintenance

#74 docs: add workflow step create amplitude model
  doc/conf.py
  doc/requirements.txt
  examples/workflow/.gitignore
  examples/workflow/1_create_model.ipynb
  examples/workflow/2_generate_data.ipynb
  tensorwaves/physics/helicityformalism/amplitude.py
Labels: Priority: Medium, documentation

#79 ci: standardize VSCode settings
  .gitignore
  .vscode/.gitignore
  .vscode/settings.json
  doc/contribute.rst
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Medium

#80 ci: set dev requirements to minimal
  requirements-dev.txt
  tests/requirements.txt
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#81 ci!: add and enforce pydocstyle check
  .pre-commit-config.yaml
  .travis.yml
  .vscode/settings.json
  doc/conf.py
  examples/python/workflow.py
  requirements-dev.txt
  setup.py
  tensorwaves/__init__.py
  tensorwaves/data/__init__.py
  tensorwaves/data/generate.py
  tensorwaves/estimator.py
  tensorwaves/interfaces.py
  tensorwaves/optimizer/__init__.py
  tensorwaves/physics/__init__.py
  tensorwaves/physics/helicityformalism/__init__.py
  tensorwaves/physics/helicityformalism/amplitude.py
  tensorwaves/physics/helicityformalism/kinematics.py
  tox.ini
Labels: :bulb: DX, :clock1: Easy, :exclamation: Follow-up, :warning: Medium

#82 ci!: enforce flake8 through Travis
  .travis.yml
  examples/python/workflow.py
  requirements-dev.txt
  tox.ini
Labels: :bulb: DX, :clock1: Easy, :exclamation: Follow-up, :warning: Medium

#83 ci!: enforce mypy check through Travis
  .travis.yml
  .vscode/settings.json
  setup.py
  tensorwaves/data/generate.py
  tensorwaves/interfaces.py
  tensorwaves/physics/helicityformalism/kinematics.py
  tests/__init__.py
  tests/data/__init__.py
  tests/physics/__init__.py
  tests/physics/helicityformalism/__init__.py
  tox.ini
Labels: :bulb: DX, :bulb: Maintenance, :clock1: Easy, :grey_exclamation: Question, :warning: Medium

#84 ci!: enforce pylint check through Travis
  .pre-commit-config.yaml
  .pylintrc
  .travis.yml
  examples/python/workflow.py
  tensorwaves/physics/helicityformalism/amplitude.py
  tests/physics/helicityformalism/test_amplitude.py
  tox.ini
Labels: :bulb: DX, :bulb: Maintenance, :clock1: Medium, :exclamation: Follow-up, :warning: Medium

#85 ci: enforce pre-commit checks through Travis
  .pre-commit-config.yaml
  .travis.yml
  doc/contribute.rst
Labels: :bulb: DX, :clock1: Easy, :exclamation: Follow-up, :warning: Medium

#86 ci!: add and enforce rstcheck
  .pre-commit-config.yaml
  .vscode/settings.json
  doc/install/install.rst
  doc/install/virtual-environment.rst
  requirements-dev.txt
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#87 ci!: add and enforce Prettier formatting
  .pre-commit-config.yaml
  .prettierrc
  .vscode/settings.json
  README.md
  doc/_templates/genindex.html
  doc/_templates/layout.html
Labels: :bulb: DX, :clock1: Easy, :exclamation: Follow-up, :warning: Low

#88 feat: add support for canonical formalism
  requirements.txt
  setup.py
  tensorwaves/physics/helicityformalism/amplitude.py
  tests/physics/helicityformalism/test_canonical.py
  tox.ini
Labels: :bulb: Enhancement

#89 ci: run pytest and pytest-cov from root dir
  .travis.yml
  .vscode/settings.json
  doc/contribute.rst
  doc/install/install.rst
  tests/.coveragerc
  tests/pytest.ini
  tox.ini
Labels: :bulb: DX, :bulb: Docs, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#92 ci: make pydocstyle work in vscode
  .pylintrc
  .vscode/settings.json
  tests/data/test_generate.py
  tests/physics/helicityformalism/test_amplitude.py
  tests/physics/helicityformalism/test_canonical.py
  tests/physics/helicityformalism/test_helicityangles.py
  tests/tox.ini
  tox.ini
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#93 ci!: set up tox test environments
  .gitignore
  .pre-commit-config.yaml
  README.md
  doc/contribute.rst
  doc/index.rst
  doc/requirements.txt
  requirements-dev.txt
  tests/requirements.txt
  tox.ini
Labels: :bulb: DX, :clock2: Easy, :warning: Medium

#94 chore: remove particle_list.yaml
  tensorwaves/particle_list.yaml
Labels: :bulb: Maintenance, :clock1: Trivial, :warning: Low

#95 fix: update amplitude model recipe structure
  codecov.yml
  examples/intensity-recipe.yaml
  tensorwaves/physics/helicityformalism/_recipe_tools.py
  tensorwaves/physics/helicityformalism/amplitude.py
  tensorwaves/physics/helicityformalism/kinematics.py
  tests/.gitignore
  tests/recipe/__init__.py
  tests/recipe/test_amplitude_creation.py
  tests/requirements.txt
  tox.ini
Labels: :bulb: DX, :bulb: Enhancement, :clock3: Medium, :grey_question: Question, :warning: High

#97 docs: let generate data notebook use Step 1
  examples/workflow/2_generate_data.ipynb
Labels: :bulb: Docs, :clock2: Easy, :warning: Medium

#98 docs: add section on RTD PR build
  README.md
  doc/contribute.rst
  doc/index.rst
  doc/install.rst
  tox.ini
Labels: :bulb: DX, :bulb: Docs, :clock1: Trivial, :warning: Low

#101 docs: write "Step 3: Perform fit"
  doc/conf.py
  doc/contribute.rst
  examples/workflow/.gitignore
  examples/workflow/1_create_model.ipynb
  examples/workflow/2_generate_data.ipynb
  examples/workflow/3_perform_fit.ipynb
Labels: :bulb: Docs, :clock2: Easy, :warning: Medium

#104 ci: define vscode extensions
  .vscode/extensions.json
  doc/contribute.rst
Labels: :bulb: DX, :clock1: Trivial, :warning: Medium
