Repository ComPWA/tensorwaves, pull requests merged in 2020-04, with the labels that each got.

#32 ci: add codecov config
  codecov.yml
Labels: Priority: Medium, Type: Maintenance

#30 feat: add interfaces
  tensorwaves/interfaces.py
  tox.ini
Labels: Priority: Critical

#27 docs: switch to RTD and improve website
  .editorconfig
  .readthedocs.yml
  CONTRIBUTING.md
  README.md
  doc/Makefile
  doc/_templates/genindex.html
  doc/_templates/layout.html
  doc/_templates/module.rst_t
  doc/_templates/package.rst_t
  doc/_templates/toc.rst_t
  doc/api.rst
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  doc/install/get-the-source-code.rst
  doc/install/install.rst
  doc/install/virtual-environment.rst
  doc/installation.rst
  doc/requirements.txt
  tensorwaves/expertsystem/amplitude/canonicaldecay.py
  tensorwaves/expertsystem/solvers/constraint/__init__.py
  tensorwaves/expertsystem/state/particle.py
  tensorwaves/expertsystem/ui/system_control.py
Labels: Priority: Medium, documentation

#43 ci: ignore missing docstring init and method
  .pylintrc
  tox.ini
Labels: Priority: Medium, Type: Maintenance

#42 build: drop Python 3.5 support
  .travis.yml
  environment.yml
  setup.py
Labels: Priority: Medium, Type: Maintenance

#39 feat: implement basic kinematics functionality of the helicity formalism
  .pylintrc
  doc/conf.py
  tensorwaves/physics/helicityformalism/kinematics.py
  tests/physics/helicityformalism/test_helicityangles.py
  tox.ini
Labels: Priority: High, Type: Enhancement

#46 docs: add documentation build status badge
  README.md
  doc/conf.py
  doc/index.rst
Labels: documentation

#47 docs!: change documentation policy
  .pylintrc
  doc/conf.py
  doc/requirements.txt
  tox.ini
Labels: documentation

#49 style: add black formatting configuration
  .editorconfig
  .pre-commit-config.yaml
  .pylintrc
  doc/contribute.rst
  pyproject.toml
  requirements-dev.txt
  tox.ini
Labels: Type: Maintenance

#48 ci: add mypy configuration and pre-commit hook
  .gitignore
  .pre-commit-config.yaml
  requirements-dev.txt
  tensorwaves/interfaces.py
  tox.ini
Labels: Priority: Medium, Type: Maintenance

#58 docs: add tensorflow sphinx object inventory
  doc/conf.py
  doc/requirements.txt
  doc/tensorflow.txt
Labels: Priority: High
