Repository ComPWA/tensorwaves, pull requests merged in 2020-07, with the labels that each got.

#105 ci: add cspell support
  .editorconfig
  .pre-commit-config.yaml
  .prettierignore
  .travis.yml
  .vscode/settings.json
  cspell.json
  doc/contribute.rst
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#109 style!: fix all cspell errors
  .travis.yml
  cspell.json
  doc/api.rst
  doc/contribute.rst
  doc/index.rst
  doc/install/install.rst
  doc/usage/.gitignore
  examples/intensity-recipe.yaml
  examples/python/workflow.py
  examples/workflow/1_create_model.ipynb
  examples/workflow/2_generate_data.ipynb
  examples/workflow/3_perform_fit.ipynb
  tensorwaves/data/generate.py
  tensorwaves/data/tf_phasespace.py
  tensorwaves/optimizer/minuit.py
  tensorwaves/physics/__init__.py
  tensorwaves/physics/helicity_formalism/__init__.py
  tensorwaves/physics/helicity_formalism/_recipe_tools.py
  tensorwaves/physics/helicity_formalism/amplitude.py
  tensorwaves/physics/helicity_formalism/kinematics.py
  tests/data/test_generate.py
  tests/physics/helicityformalism/test_amplitude.py
  tests/physics/helicityformalism/test_canonical.py
  tests/physics/helicityformalism/test_helicityangles.py
  tests/recipe/__init__.py
  tests/recipe/test_amplitude_creation.py
Labels: :bulb: DX, :clock2: Easy, :warning: Medium

#110 build: single source of truth for dependencies
  .pre-commit-config.yaml
  .readthedocs.yml
  .travis.yml
  cspell.json
  doc/contribute.rst
  doc/install.rst
  doc/install/get-the-source-code.rst
  doc/install/install.rst
  doc/install/virtual-environment.rst
  doc/requirements.txt
  environment.yml
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
  tests/requirements.txt
  tox.ini
Labels: :bulb: DX, :bulb: Maintenance, :clock2: Easy, :warning: High

#108 fix: remove cast to int of helicity values
  tensorwaves/physics/helicity_formalism/amplitude.py
Labels: :clock1: Trivial, :warning: Critical, Bug

#111 feat: add analytical continuation for Breit Wigner
  setup.cfg
  tensorwaves/physics/helicity_formalism/amplitude.py
Labels: :bulb: Enhancement, :clock1: Trivial, :warning: High

#112 docs: add note about fixing parameters
  doc/install.rst
  examples/workflow/1_create_model.ipynb
  examples/workflow/3_perform_fit.ipynb
  setup.cfg
Labels: :bulb: Docs, :clock2: Easy, :warning: High

#115 docs: git clone over HTTP
  doc/contribute.rst
  doc/install.rst
Labels: :bulb: Docs, :clock1: Trivial, :warning: Low

#116 build: upgrade to expertsystem 0.2.0
  doc/.gitignore
  doc/conf.py
  doc/install.rst
  doc/usage.rst
  doc/usage/.gitignore
  examples/workflow/1_create_model.ipynb
  setup.cfg
  tensorwaves/physics/helicity_formalism/amplitude.py
  tests/recipe/__init__.py
  tox.ini
Labels: :bulb: Docs, :bulb: Enhancement, :clock2: Easy, :warning: Medium
