Repository ComPWA/tensorwaves, pull requests merged in 2020-11, with the labels that each got.

#144 ci: add GitHub workflow for epic branches
  .github/workflows/ci-epic.yml
Labels: 🖱️ DX

#149 ci: build wheel and fix GitHub deploy
  .github/workflows/cd.yml
  pyproject.toml
Labels: Bug

#150 build: upgrade to expertsystem 0.6.3
  docs/conf.py
  setup.cfg
  tests/conftest.py
Labels: Bug

#152 fix: only determine doc version if available
  docs/conf.py
Labels: Bug, 🖱️ DX

#153 fix: correctly compute tqdm iterations
  src/tensorwaves/data/generate.py
Labels: Bug

#155 feat: add variable logging functionality using tf
  .gitignore
  docs/usage/3_perform_fit.ipynb
  src/tensorwaves/optimizer/logging.py
  src/tensorwaves/optimizer/minuit.py
Labels: 💡 Enhancement

#156 feat: print execute time in optimize
  src/tensorwaves/optimizer/minuit.py
Labels: 💡 Enhancement

#164 refactor: log optimize process via callbacks
  cspell.json
  docs/conf.py
  docs/usage/3_perform_fit.ipynb
  setup.cfg
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/logging.py
  src/tensorwaves/optimizer/minuit.py
Labels: 💡 Enhancement

#154 feat: add intermediate result YAML saving
  docs/usage/3_perform_fit.ipynb
  src/tensorwaves/optimizer/callbacks.py
Labels: 💡 Enhancement

#168 feat!: generate deterministic data samples
  cspell.json
  docs/tensorflow.txt
  setup.cfg
  src/tensorwaves/data/generate.py
  src/tensorwaves/data/tf_phasespace.py
  src/tensorwaves/interfaces.py
  tests/data/test_generate.py
  tests/data/test_tf_phasespace.py
  tox.ini
Labels: 💡 Enhancement

#169 test!: define tests for Minuit2.optimize
  .vscode/settings.json
  codecov.yml
  src/tensorwaves/optimizer/minuit.py
  tests/conftest.py
  tests/data/test_generate.py
  tests/optimizer/__init__.py
  tests/optimizer/test_minuit.py
  tests/recipe/test_amplitude_creation.py
  tox.ini
Labels: 🔨 Maintenance

#173 feat: add CSVSummary callback
  cspell.json
  docs/.gitignore
  docs/usage/3_perform_fit.ipynb
  src/tensorwaves/optimizer/callbacks.py
Labels: 💡 Enhancement

#174 fix: copy initial parameters in optimize call
  docs/usage/3_perform_fit.ipynb
  src/tensorwaves/optimizer/minuit.py
  tests/conftest.py
  tests/optimizer/test_minuit.py
  tests/recipe/test_amplitude_creation.py
  tests/test_estimator.py
Labels: Bug, 🔨 Maintenance

#175 docs!: outsource develop to PWA pages
  .gitignore
  CONTRIBUTING.md
  docs/.gitignore
  docs/_static/favicon.ico
  docs/api.rst
  docs/conf.py
  docs/develop.rst
  docs/index.md
  docs/install.md
  docs/install.rst
  pyrightconfig.json
Labels: 📝 Docs

#176 build!: upgrade and reorganize dependencies
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .pylintrc
  .vscode/settings.json
  codecov.yml
  commitlint.config.js
  cspell.json
  docs/conf.py
  setup.cfg
  tests/output/.gitignore
  tests/output/.gitkeep
  tox.ini
Labels: 🔨 Maintenance, 🖱️ DX

#178 ci: implement markdownlint pre-commit hook
  .editorconfig
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  cspell.json
  setup.cfg
  tox.ini
Labels: 🖱️ DX

#177 feat: implement Loadable callback
  cspell.json
  docs/usage/3_perform_fit.ipynb
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/minuit.py
  tests/conftest.py
  tests/optimizer/test_callbacks.py
  tests/optimizer/test_minuit.py
Labels: 💡 Enhancement

#180 fix: remove default dynamics
  .vscode/settings.json
  docs/conf.py
  docs/install.md
  docs/usage/1_create_model.ipynb
  docs/usage/3_perform_fit.ipynb
  examples/intensity-recipe.yaml
  setup.cfg
  src/tensorwaves/physics/helicity_formalism/amplitude.py
  tests/conftest.py
  tests/recipe/test_amplitude_creation.py
Labels: Bug
