Repository ComPWA/tensorwaves, pull requests merged in 2020-08, with the labels that each got.

#121 feat: add default dynamics RelativisticBW
  tensorwaves/physics/helicity_formalism/amplitude.py
Labels: Bug

#123 fix: prevent multiple entries of the same invariant mass
  tensorwaves/physics/helicity_formalism/kinematics.py
Labels: 💡 Enhancement

#124 ci!: switch to GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
  .github/workflows/pr-linting.yml
  .github/workflows/pypi.yml
  .travis.yml
  README.md
  commitlint.config.js
  cspell.json
  doc/index.rst
  doc/mypy_badge.svg
Labels: 🖱️ DX

#126 ci!: equalize dev set-up
  .github/workflows/ci.yml
  .gitignore
  .markdownlint.json
  .pre-commit-config.yaml
  .prettierrc
  .pylintrc
  .readthedocs.yml
  .vscode/extensions.json
  .vscode/settings.json
  codecov.yml
  cspell.json
  doc/.gitignore
  doc/api.rst
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  doc/install.rst
  examples/workflow/.gitignore
  labels.toml
  setup.cfg
  tests/.gitignore
  tox.ini
Labels: 📝 Docs, 🖱️ DX

#128 build!: upgrade to TF2.3
  .github/workflows/ci.yml
  .gitignore
  doc/conf.py
  environment.yml
  examples/intensity-recipe.yaml
  examples/workflow/1_create_model.ipynb
  examples/workflow/2_generate_data.ipynb
  examples/workflow/3_perform_fit.ipynb
  pyproject.toml
  setup.cfg
  tensorwaves/data/tf_phasespace.py
  tensorwaves/physics/helicity_formalism/amplitude.py
Labels: 💡 Enhancement

#120 build!: upgrade to expertsystem 0.4.0a1
  .github/workflows/ci.yml
  README.md
  doc/conf.py
  doc/index.rst
  environment.yml
  examples/python/workflow.py
  examples/workflow/1_create_model.ipynb
  examples/workflow/3_perform_fit.ipynb
  pyproject.toml
  setup.cfg
  tensorwaves/physics/helicity_formalism/amplitude.py
  tests/data/test_generate.py
  tests/recipe/__init__.py
  tests/recipe/test_amplitude_creation.py
Labels: 💡 Enhancement

#129 ci!: automate release notes
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  doc/contribute.rst
Labels: 📝 Docs, 🖱️ DX
