Repository ComPWA/tensorwaves, pull requests merged in 2020-05, with the labels that each got.

#63 feat!: implement Minuit2 optimization functionality
  doc/conf.py
  examples/test.py
  requirements.txt
  tensorwaves/__init__.py
  tensorwaves/data/__init__.py
  tensorwaves/data/generate.py
  tensorwaves/estimator.py
  tensorwaves/optimizer/__init__.py
  tensorwaves/optimizer/minuit.py
  tensorwaves/physics/helicityformalism/kinematics.py
Labels: Priority: High, Type: Enhancement

#65 docs: add Jupyter notebook example
  .travis.yml
  CONTRIBUTING.md
  README.md
  doc/.gitignore
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  doc/requirements.txt
  doc/usage.rst
  doc/usage/.gitignore
  examples/jupyter/generate.ipynb
  examples/python/workflow.py
  requirements.txt
  tensorwaves/data/tf_phasespace.py
  tests/requirements.txt
Labels: Priority: High, documentation

#66 refactor: improve modularity of helicity formalism amplitudes
  examples/intensity-recipe.yaml
  tensorwaves/physics/helicityformalism/amplitude.py
  tests/physics/helicityformalism/test_amplitude.py
  tox.ini
Labels: Priority: Medium, Type: Maintenance
