Repository ComPWA/tensorwaves, pull requests merged in 2021-12, with the labels that each got.

#359 ci: switch to nbmake
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  docs/usage/step3.ipynb
  pytest.ini
  setup.cfg
  src/tensorwaves/function/__init__.py
  tox.ini
Labels: 📝 Docs, 🖱️ DX

#360 test: add fast optimize test
  .flake8
  .github/workflows/ci-tests.yml
  codecov.yml
  docs/usage.ipynb
  docs/usage/basics.ipynb
  docs/usage/step3.ipynb
  pytest.ini
  src/tensorwaves/optimizer/__init__.py
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/minuit.py
  src/tensorwaves/optimizer/scipy.py
  tests/unit/data/test_generate.py
  tests/unit/optimizer/test_fit_simple_model.py
  tox.ini
Labels: 🔨 Maintenance

#361 fix: jit-compile recombined fast_lambdify function
  docs/usage/step3.ipynb
  src/tensorwaves/_backend.py
  src/tensorwaves/function/sympy.py
  tests/unit/function/test_sympy.py
Labels: Bug

#362 refactor: simplify public backend signatures
  src/tensorwaves/__init__.py
  src/tensorwaves/_backend.py
  src/tensorwaves/estimator.py
  src/tensorwaves/function/sympy.py
  src/tensorwaves/interface.py
  tests/unit/test_backend.py
Labels: 📝 Docs, ⚠️ Interface

#363 feat: speed up imports
  docs/abbreviate_signature.py
  src/tensorwaves/data/__init__.py
  src/tensorwaves/data/phasespace.py
  src/tensorwaves/data/transform.py
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/scipy.py
  tests/unit/test_backend.py
  tox.ini
Labels: 🔨 Maintenance

#364 fix: write Optimizer and Estimator type
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/minuit.py
  src/tensorwaves/optimizer/scipy.py
  tests/unit/optimizer/test_fit_simple_model.py
Labels: Bug, 💡 Feature

#365 fix: lambdify ComplexSqrt to TensorFlow
  .flake8
  pytest.ini
  src/tensorwaves/estimator.py
  src/tensorwaves/function/_backend.py
  src/tensorwaves/function/sympy.py
  tests/unit/function/test_ampform.py
  tests/unit/function/test_backend.py
  tests/unit/test_backend.py
Labels: Bug

#367 ci: merge test jobs
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .cspell.json
  .github/workflows/cd.yml
  .github/workflows/ci-tests.yml
  .github/workflows/requirements-pr.yml
  .pre-commit-config.yaml
  pytest.ini
  tox.ini
Labels: 🖱️ DX

#366 ci: avoid callbacks if unspecified
  pytest.ini
  setup.cfg
  src/tensorwaves/interface.py
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/minuit.py
  src/tensorwaves/optimizer/scipy.py
  tests/unit/optimizer/test_minuit.py
Labels: 🔨 Maintenance

#369 build: reduce dependencies in style requirements
  setup.cfg
  src/tensorwaves/function/_backend.py
Labels: 🖱️ DX

#370 ci: speed up pytest collect
  benchmarks/ampform.py
  pytest.ini
  tests/conftest.py
  tests/data/test_generate.py
  tests/data/test_phasespace.py
  tox.ini
Labels: 🖱️ DX

#371 refactor: generalize SymPy printer implementation
  src/tensorwaves/function/sympy.py
Labels: 🔨 Maintenance

#374 feat: lambdify with common sub-expressions
  src/tensorwaves/function/sympy.py
  tests/function/test_sympy.py
Labels: 💡 Feature

#375 fix: forward use_cse arguments
  src/tensorwaves/function/sympy.py
Labels: Bug

#345 refactor: adapt implementation to AmpForm v0.12.x
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .github/workflows/cd.yml
  .pre-commit-config.yaml
  .pylintrc
  benchmarks/ampform.py
  docs/abbreviate_signature.py
  docs/usage.ipynb
  docs/usage/analytic-continuation.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
  pytest.ini
  setup.cfg
  src/tensorwaves/data/__init__.py
  src/tensorwaves/data/phasespace.py
  src/tensorwaves/data/transform.py
  src/tensorwaves/function/__init__.py
  src/tensorwaves/function/_backend.py
  src/tensorwaves/function/sympy/__init__.py
  src/tensorwaves/function/sympy/_printer.py
  src/tensorwaves/interface.py
  tests/data/test_generate.py
  tests/data/test_phasespace.py
  tests/data/test_transform.py
  tests/function/test_ampform.py
  tests/function/test_function.py
  tests/function/test_sympy.py
Labels: 🔨 Maintenance

#378 feat: implement get_source_code function
  docs/usage/basics.ipynb
  docs/usage/step3.ipynb
  src/tensorwaves/data/__init__.py
  src/tensorwaves/data/transform.py
  src/tensorwaves/estimator.py
  src/tensorwaves/function/__init__.py
  src/tensorwaves/function/sympy/__init__.py
  tests/function/test_function.py
  tests/test_estimator.py
Labels: 💡 Feature

#380 build: make ampform an optional dependency
  docs/install.md
  setup.cfg
Labels: ⚠️ Interface

#381 docs: add GPU installation tips
  docs/abbreviate_signature.py
  docs/conf.py
  docs/install.md
  docs/usage/step3.ipynb
  setup.cfg
Labels: 📝 Docs

#382 ci: update pip constraints and pre-commit config
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .github/workflows/linkcheck.yml
  .pre-commit-config.yaml
  docs/conf.py
  docs/usage.ipynb
  docs/usage/step3.ipynb
Labels: 🖱️ DX

#383 build: set minimal dependencies sympy and pyyaml
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  setup.cfg
Labels: 🔨 Maintenance

#385 ci: update pip constraints and pre-commit config
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .pre-commit-config.yaml
Labels: 🖱️ DX

#386 ci: update pip constraints and pre-commit config
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .pre-commit-config.yaml
  docs/conf.py
  setup.cfg
Labels: 🖱️ DX

#387 feat!: implement chi-squared estimator
  .cspell.json
  docs/usage.ipynb
  docs/usage/chi-squared.ipynb
  src/tensorwaves/estimator.py
  src/tensorwaves/interface.py
  tests/test_estimator.py
Labels: 📝 Docs, 💡 Feature

#388 docs: illustrate binned and unbinned fit
  .cspell.json
  docs/usage.ipynb
  docs/usage/binned-fit.ipynb
  docs/usage/unbinned-fit.ipynb
  src/tensorwaves/estimator.py
Labels: 📝 Docs

#389 docs!: merge and isolate AmpForm notebooks
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .cspell.json
  .pre-commit-config.yaml
  docs/.gitignore
  docs/amplitude-analysis.ipynb
  docs/amplitude-analysis/analytic-continuation.ipynb
  docs/index.md
  docs/usage.ipynb
  docs/usage/basics.ipynb
  docs/usage/faster-lambdify.ipynb
  docs/usage/step1.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
  setup.cfg
  src/tensorwaves/interface.py
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/scipy.py
  tox.ini
Labels: 📝 Docs

#390 docs: illustrate expression tree optimization
  .cspell.json
  docs/amplitude-analysis.ipynb
Labels: 📝 Docs
