Repository ComPWA/tensorwaves, pull requests merged in 2021-01, with the labels that each got.

#185 ci: automatically upgrade requirements
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
  .github/workflows/pr-linting.yml
  .github/workflows/release-drafter.yml
  .github/workflows/requirements-cron.yml
  .github/workflows/requirements-pr.yml
  .gitpod.yml
  .readthedocs.yml
  .vscode/settings.json
  cspell.json
  docs/install.md
  environment.yml
  reqs/.gitignore
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  reqs/extract_install_requires.py
  reqs/requirements-dev.in
  reqs/requirements-doc.in
  reqs/requirements-sty.in
  reqs/requirements-test.in
  reqs/upgrade.sh
  setup.cfg
  tox.ini
Labels: 🖱️ DX

#159 epic: export and import fit result
  .github/workflows/ci-epic.yml
  .github/workflows/pr-linting.yml
  .gitignore
  codecov.yml
  cspell.json
  docs/.gitignore
  docs/usage/1_create_model.ipynb
  docs/usage/2_generate_data.ipynb
  docs/usage/3_perform_fit.ipynb
  examples/workflow.py
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  setup.cfg
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/minuit.py
  tests/conftest.py
  tests/data/test_generate.py
  tests/optimizer/__init__.py
  tests/optimizer/test_callbacks.py
  tests/optimizer/test_minuit.py
  tests/recipe/test_amplitude_creation.py
  tests/test_estimator.py
  tox.ini
Labels: Epic, 💡 Enhancement

#182 test: add angular distribution tests from pycompwa
  .pylintrc
  docs/usage/2_generate_data.ipynb
  docs/usage/3_perform_fit.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/requirements-test.in
  setup.cfg
  src/tensorwaves/physics/helicity_formalism/amplitude.py
  src/tensorwaves/physics/helicity_formalism/kinematics.py
  tests/physics/helicity_formalism/.gitignore
  tests/physics/helicity_formalism/TestD1ToD0PiPi.yml
  tests/physics/helicity_formalism/TestEpemToDmD0Pip.yml
  tests/physics/helicity_formalism/test_amplitude.py
  tests/physics/helicity_formalism/test_angular_distributions.py
Labels: 💡 Enhancement

#187 fix!: use es.FormFactor in _RelativisticBreitWigner
  docs/usage/3_perform_fit.ipynb
  src/tensorwaves/physics/helicity_formalism/amplitude.py
  tests/conftest.py
  tests/data/test_generate.py
  tests/optimizer/test_callbacks.py
  tests/optimizer/test_minuit.py
Labels: Bug

#188 fix: throw invalid L error correctly
  src/tensorwaves/physics/helicity_formalism/amplitude.py
  tests/physics/helicity_formalism/test_amplitude.py
Labels: Bug

#189 fix: add mass*width factor to relBW w/o ff
  src/tensorwaves/physics/helicity_formalism/amplitude.py
  tests/data/test_generate.py
  tests/optimizer/test_minuit.py
Labels: Bug

#190 ci: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🖱️ DX

#193 ci: add issue label for interface changes
  .github/release-drafter.yml
  .github/workflows/pr-linting.yml
  .github/workflows/requirements-cron.yml
  labels.toml
Labels: 🖱️ DX

#194 test: check shape of kinematics dataset
  tests/conftest.py
  tests/optimizer/test_callbacks.py
  tests/physics/helicity_formalism/test_kinematics.py
Labels: 🖱️ DX

#197 fix: remove Python example workflow
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  docs/index.md
  docs/usage.rst
  examples/intensity-recipe.yaml
  examples/workflow.py
  pyrightconfig.json
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
Labels: 🖱️ DX

#192 refactor!: normalize function in NLL
  docs/usage/2_generate_data.ipynb
  docs/usage/3_perform_fit.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
  src/tensorwaves/estimator.py
  src/tensorwaves/physics/helicity_formalism/amplitude.py
  tests/conftest.py
  tests/recipe/test_amplitude_creation.py
  tests/test_estimator.py
Labels: ⚠️ Interface, 🔨 Maintenance

#198 build: upgarde to expertsystem 0.6.7
  docs/conf.py
  docs/usage/1_create_model.ipynb
  docs/usage/2_generate_data.ipynb
  docs/usage/3_perform_fit.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
  tests/physics/helicity_formalism/TestD1ToD0PiPi.yml
  tests/physics/helicity_formalism/TestEpemToDmD0Pip.yml
  tests/physics/helicity_formalism/test_angular_distributions.py
  tox.ini
Labels: 🖱️ DX

#199 build: upgrade to expertsystem 0.6.8
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  reqs/requirements-doc.in
  setup.cfg
Labels: 💡 Feature

#200 ci: upgrade developer dependencies
  .editorconfig
  .github/workflows/requirements-cron.yml
  .pylintrc
  cspell.json
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
Labels: 🖱️ DX

#201 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
Labels: 🖱️ DX

#202 docs: remove module visualization
  cspell.json
  docs/conf.py
  reqs/3.6/requirements-doc.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.8/requirements-doc.txt
  reqs/requirements-dev.in
  reqs/requirements-doc.in
  tox.ini
Labels: Bug, 📝 Docs
