Repository ComPWA/tensorwaves, pull requests merged in 2021-03, with the labels that each got.

#219 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
Labels: 🖱️ DX

#220 ci: automatically upgrade pre-commit hooks
  .github/workflows/requirements-cron.yml
  .pre-commit-config.yaml
  pyrightconfig.json
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
Labels: 🖱️ DX

#221 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
Labels: 🖱️ DX

#223 fix: use tqdm.autonotebook
  docs/usage/1_create_model.ipynb
  docs/usage/2_generate_data.ipynb
  docs/usage/3_perform_fit.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
  src/tensorwaves/data/generate.py
  src/tensorwaves/optimizer/minuit.py
Labels: Bug

#224 build: upgrade to expertsystem 0.6.10
  .vscode/settings.json
  docs/conf.py
  docs/usage/1_create_model.ipynb
  docs/usage/2_generate_data.ipynb
  docs/usage/3_perform_fit.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
  src/tensorwaves/physics/helicity_formalism/amplitude.py
  tests/physics/helicity_formalism/TestD1ToD0PiPi.yml
  tests/physics/helicity_formalism/TestEpemToDmD0Pip.yml
  tests/physics/helicity_formalism/test_angular_distributions.py
  tests/physics/helicity_formalism/test_kinematics.py
Labels: 🔨 Maintenance

#225 ci: allow running notebooks through tox doclive
  tox.ini
Labels: 🖱️ DX

#227 refactor: rename converter to transformer
  docs/usage.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
  src/tensorwaves/data/__init__.py
  src/tensorwaves/data/transform.py
  src/tensorwaves/estimator.py
  src/tensorwaves/interfaces.py
  src/tensorwaves/model.py
  tests/conftest.py
  tests/test_estimator.py
Labels: ⚠️ Interface

#228 build: upgrade to expertsystem v0.7.0
  .github/workflows/requirements-cron.yml
  .github/workflows/requirements-pr.yml
  cspell.json
  docs/usage.ipynb
  docs/usage/step1.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  reqs/requirements-dev.in
  setup.cfg
  src/tensorwaves/data/transform.py
  src/tensorwaves/model.py
  tests/conftest.py
Labels: 🔨 Maintenance

#229 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
Labels: 🖱️ DX

#233 ci: add collapsible_headings labextension
  reqs/3.6/requirements-dev.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.8/requirements-dev.txt
  reqs/requirements-dev.in
Labels: 🖱️ DX

#232 docs: illustrate example without expertsystem
  cspell.json
  docs/usage.ipynb
  docs/usage/basics.ipynb
Labels: 📝 Docs

#235 docs: add SciPy example to usage notebook
  cspell.json
  docs/usage.ipynb
  docs/usage/step3.ipynb
  src/tensorwaves/optimizer/callbacks.py
  tests/conftest.py
Labels: 📝 Docs

#236 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
Labels: 🖱️ DX

#234 refactor: extend Callback interface
  docs/usage/step3.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/requirements-test.in
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/minuit.py
  src/tensorwaves/optimizer/scipy.py
  tests/optimizer/__init__.py
  tests/optimizer/test_minuit.py
  tests/optimizer/test_scipy.py
Labels: ⚠️ Interface, 💡 Feature

#239 refactor: use csv.DictWriter instead of pandas
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  reqs/requirements-doc.in
  setup.cfg
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/minuit.py
  src/tensorwaves/optimizer/scipy.py
Labels: 🔨 Maintenance

#242 docs: improve optimize process plots
  docs/usage.ipynb
  docs/usage/step3.ipynb
Labels: 📝 Docs

#241 feat: add iteration callback support for scipy+csv
  docs/usage/step3.ipynb
  src/tensorwaves/optimizer/callbacks.py
  src/tensorwaves/optimizer/scipy.py
Labels: 💡 Feature

#243 docs: render figures as SVG
  docs/usage.ipynb
  docs/usage/basics.ipynb
  docs/usage/step1.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
Labels: 📝 Docs

#244 feat: extract intensity components
  cspell.json
  docs/usage/step1.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
  src/tensorwaves/model.py
  src/tensorwaves/physics.py
  tests/conftest.py
  tests/test_model.py
  tests/test_physics.py
Labels: 💡 Feature

#245 feat: support lambdify to tensorflow
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-extras.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-extras.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-extras.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
  src/tensorwaves/model.py
  src/tensorwaves/optimizer/minuit.py
Labels: 💡 Feature

#248 build: upgrade to expertsystem v0.7.1
  docs/conf.py
  docs/usage.ipynb
  docs/usage/step1.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-extras.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-extras.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-extras.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
  src/tensorwaves/physics.py
  tests/conftest.py
Labels: 🔨 Maintenance

#250 docs: add install cells for Google Colab
  .pre-commit-config.yaml
  .pre-commit-hooks/fix_first_nbcell.py
  .pre-commit-hooks/fix_nbformat_version.py
  docs/usage.ipynb
  docs/usage/basics.ipynb
  docs/usage/step1.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
Labels: 📝 Docs, 🖱️ DX

#251 fix: avoid cell magic in colab cell
  .pre-commit-config.yaml
  .pre-commit-hooks/fix_first_nbcell.py
  docs/usage.ipynb
  docs/usage/basics.ipynb
  docs/usage/step1.ipynb
  docs/usage/step2.ipynb
  docs/usage/step3.ipynb
Labels: Bug

#252 fix: improve output of YAMLSummary
  src/tensorwaves/optimizer/callbacks.py
Labels: Bug

#253 fix: load complex parameter values from CSV
  src/tensorwaves/optimizer/callbacks.py
  tests/conftest.py
Labels: Bug

#247 feat: add caching of constant sub expressions in SympyModels
  .github/workflows/ci-epic.yml
  .github/workflows/ci.yml
  src/tensorwaves/estimator.py
  src/tensorwaves/model.py
  tests/test_model.py
Labels: 💡 Feature

#255 ci: upgrade developer dependencies
  .vscode/settings.json
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-extras.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-extras.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-extras.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
Labels: 🖱️ DX

#256 ci: add cspell pyright and ComPWA/meta pre-commits
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .pre-commit-hooks/fix_first_nbcell.py
  .pre-commit-hooks/fix_nbformat_version.py
  cspell.json
  tox.ini
Labels: 🖱️ DX

#254 refactor: wrap fit result in class
  .pylintrc
  cspell.json
  docs/usage.ipynb
  docs/usage/basics.ipynb
  docs/usage/step3.ipynb
  src/tensorwaves/interfaces.py
  src/tensorwaves/optimizer/minuit.py
  src/tensorwaves/optimizer/scipy.py
  tests/conftest.py
  tests/optimizer/test_callbacks.py
  tests/optimizer/test_minuit.py
  tests/optimizer/test_scipy.py
  tests/test_estimator.py
Labels: ⚠️ Interface
